name: FLUX TEST

on:
  workflow_dispatch:

jobs:
  fluxpipe:
    runs-on: ubuntu-latest
    name: Run a Flux Script
    steps:
      - name: Flux Run
        id: flux
        uses: lmangani/flux-github-action@use-latest-ghcr
        with:
          flux-script: 'import "array" import "runtime" array.from(rows: [{version: runtime.version()}])'
      - name: Flux Result
        run: echo "${{ steps.flux.outputs.result }}"
