name: FLUX TEST

on:
  workflow_dispatch:

jobs:
  fluxpipe:
    runs-on: ubuntu-latest
    steps:
    - uses: lmangani/flux-github-action@use-latest-ghcr
    - run: curl localhost:8086 -sS
    - run: |
        curl -XPOST localhost:8086/api/v2/query -sS \
        -H 'Accept:application/csv' \
        -H 'Content-type:application/vnd.flux' \
        -d 'import "array" import "runtime" array.from(rows: [{version: runtime.version()}])'
